name: Daily workflow

on:
  schedule:
    - cron: "0 1 * * *" #The GitHub Actions workflow will now run daily at 1 AM.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: python send_email.py

        #run: ./build.sh
